### ISSUE TITLE
pointtolayer makes first geojson feature parentLayer

### ISSUE THREAD

**Issue by fritzvd** [glenrobertson/leaflet-tilelayer-geojson#14]
Hi,

We've been implementing some clickhandlers on this very fine TileLayer of yours. But I could not exactly pinpoint what the problem I think I found a little bug.

When I add a tilelayer with multiple features the first feature becomes a parentLayer. All of the other layers become part of this parentLayer.

This means that whenever I click on the layer it produces 2 events. Where one is always from the parent, the second from the specific child I'm pressing.

I added a little snippet with the console output in Chrome below. In the example I have 4 features that I add. The first feature is used as parent and also gets itself as a child.

![geojsonlayers](https://f.cloud.github.com/assets/160328/2398254/eefd284a-a9f3-11e3-8e7a-8f97e46462a5.png)

**Comment by tim-lan** [comment]
same problem as @fritzvd here.
