### ISSUE TITLE
Add withCredentials to XMLHttpRequest

### ISSUE THREAD

**Issue by sijpesteijn** [glenrobertson/leaflet-tilelayer-geojson#17]
Hi,

Excellent plugin. I have one issue though.

We need to do CORS and need to set the withCredentials=true on the XMLHttpRequest object. Could you make this an option for the plugin. Or set it default to true. It should not cause problems for non CORS requests. 
Thanx in advance, regards, Gijs

**Comment by glenrobertson** [comment]
Closing this since there is no implementation. Please feel free to re-open if you have a pull request :smile:
