### ISSUE TITLE
Markerclusterer

### ISSUE THREAD

**Issue by robotnic** [glenrobertson/leaflet-tilelayer-geojson#24]
Is there an easy way to use this lib together with (client side) markerclusterer? 

https://github.com/Leaflet/Leaflet.markercluster

**Comment by glenrobertson** [comment]
Hey @robotnic. Sorry for the long delay. If this is still relevant, take a look at @baxford's implementation, which implements clustering: https://github.com/baxford/leaflet-tilelayer-geojson
