### ISSUE TITLE
Circle over tilelayer

### ISSUE THREAD

**Issue by nflsalex** [glenrobertson/leaflet-tilelayer-geojson#25]
Hi,

I am using titelayer as background and circle to show our data. But tilelayer is always on top of circle, How can I fix that? Thanks

Yilun

**Comment by allthesignals** [comment]
Did you try using [`bringToFront()`](http://leafletjs.com/reference.html#path-bringtofront) on whatever the circle is? TileLayer also has this type of functionality (`bringToBack`).

I've also found it's help to wrap this sort of thing in a callback that's registered on the layer's `load` event:
```
geojsonTileLayer.on('load', function() {
  //some behavior
});
```

**Comment by nflsalex** [comment]
@allthesignals 
if I add geojsonTileLayer.bringToBack();
there is an error: Cannot read property '_panes' of undefined

**Comment by allthesignals** [comment]
@nflsalex Could you post a snippet of your code for some context?

**Comment by nflsalex** [comment]
@allthesignals  Thanks!

var map = L.map('map').setView([39.7326,-98.9196], 5);
var style = {
   // "clickable": true,
    "color": "#0354A5",
    "fillColor": "#0354A5",
    "weight": 0.5,
    "opacity": 0.5,
    "fillOpacity": 0.3
};
var hoverStyle = {
    "fillOpacity": 0.5
};

var geojsonURL = 'http://polymaps.appspot.com/state/{z}/{x}/{y}.json';
var geojsonTileLayer = new L.TileLayer.GeoJSON(geojsonURL, {
        clipTiles: true,
        unique: function (feature) {
            return feature.id; 
        }
    }, {
        style: style,
    }
);
geojsonTileLayer.setZIndex(-1)
map.addLayer(geojsonTileLayer, true);
For circle:
$.each(data, function(index, value) {
L.circle([value[1], value[2]], 60000, {
fillColor: getColorbyValue(value[3], min, max), 
fillOpacity: 1,
stroke: false
}).bindPopup(value[0] + ' (' + value[3] + ')').addTo(map);
});
