### ISSUE TITLE
Not compatible with 1.0-beta1

### ISSUE THREAD

**Issue by j16sdiz** [glenrobertson/leaflet-tilelayer-geojson#27]
This plugin is not compatible with leaflet 1.0 beta1

**Comment by dreamfalcon** [comment]
Just a question.
Are there plans to update the plugin to leaflet 1 in a near future?
Just had a look at the code and many things changed :/

**Comment by ghybs** [comment]
Same as https://github.com/glenrobertson/leaflet-tilelayer-geojson/issues/39
