### ISSUE TITLE
About maintainer on npm

### ISSUE THREAD

**Issue by kennynaoh** [glenrobertson/leaflet-tilelayer-geojson#32]
Hello @glenrobertson ,
I am the member in [cdnjs](https://github.com/cdnjs/cdnjs) project.
We want to host this library.
Are you the maintainer of this library on [npm](https://www.npmjs.com/package/leaflet-tilelayer-geojson)?
Thanks.

https://github.com/cdnjs/cdnjs/issues/6746
https://github.com/cdnjs/cdnjs/pull/7753#issuecomment-216118884

**Comment by glenrobertson** [comment]
Yes

**Comment by glenrobertson** [comment]
I misunderstood this. I maintain this library but someone else I do not know has put it on npm. 
This user: https://www.npmjs.com/~kernel_daemon

**Comment by glenrobertson** [comment]
It appears @vnnv owns it

**Comment by kennynaoh** [comment]
Thanks

**Comment by vnnv** [comment]
Need help?

**Comment by glenrobertson** [comment]
@vnnv I think it's all good. He just wanted to merge https://github.com/cdnjs/cdnjs/pull/7753
